# Generated by Django 5.2.8 on 2025-12-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Urgent", "Urgent"),
                ],
                max_length=10,
            ),
        ),
    ]
