# Generated by Django 5.2.8 on 2025-12-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_alter_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
