# Generated by Django 5.2.8 on 2025-12-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0003_worker_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
